version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: MyEduConnect_db
    environment:
      # Fix weak credentials by enforcing a strong complex password 
      MYSQL_ROOT_PASSWORD: dtBs_P@ssw0rd_127v6_Secure!
      MYSQL_DATABASE: MyEduConnect_db
    # 1. Fix exposure of DB Port using localhost whitelist
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      # This points to the init.sql we drafted earlier to build your vulnerable tables
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  adminer:  # <--- This must be aligned with 'db:'
    image: adminer
    container_name: MyEduConnect_db_admin
    restart: always
    ports:
      # 2. Fixed exposed admin service using localhost whitelisting
      - "127.0.0.1:8080:8080"

  # 3. Delete vulnerable_host (port 2222), closed ssh service
      
